src/api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from tastypie.api import Api

from .resources import (UserResource, EmailAddressResource, MessageResource,
                     RevisionResource, TicketResource, WikiResource)
from .views import VoteView


api = Api(api_name='v1')
api.register(UserResource())
api.register(EmailAddressResource())
api.register(MessageResource())
api.register(RevisionResource())
api.register(TicketResource())
api.register(WikiResource())


urlpatterns = patterns('',
    url(r'message/(?P<msg_id>\d+)/vote$', VoteView.as_view()),

    # tastypie urls
    url(r'', include(api.urls)),
)

src/colab/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib import admin

from accounts.models import User
from search.forms import ColabSearchForm
from super_archives.models import Message


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'home.views.index', name='home'),
    url(r'^robots.txt$', 'home.views.robots', name='robots'),

    url(r'^open-data/$', TemplateView.as_view(template_name='open-data.html'),
        name='opendata'),

    url(r'^search/', include('search.urls')),
    url(r'^archives/', include('super_archives.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^rss/', include('rss.urls')),

    url(r'^user/', include('accounts.urls')),    # Kept for backwards compatibility
    url(r'^signup/', include('accounts.urls')),  # (same here) TODO: move to nginx
    url(r'^account/', include('accounts.urls')),

    url(r'', include('django_browserid.urls')),

    url(r'^planet/', include('feedzilla.urls')),

    url(r'paste/', include('dpaste.urls.dpaste')),

    # Uncomment the next line to enable the admin:
    url(r'^colab/admin/', include(admin.site.urls)),

    url(r'^', include('proxy.urls')),
)

if settings.DEBUG:
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/super_archives/urls.py
from django.conf.urls import patterns, include, url

from .views import EmailView, EmailValidationView, ThreadView, \
                   ThreadDashboardView


urlpatterns = patterns('super_archives.views',
    url(r'thread/(?P<mailinglist>[-\w]+)/(?P<thread_token>[-\w]+)$',
        ThreadView.as_view(), name="thread_view"),
    url(r'thread/$', ThreadDashboardView.as_view(), name='thread_list'),
    url(r'manage/email/validate/?$', EmailValidationView.as_view(),
                                     name="archive_email_validation_view"),
    url(r'manage/email/(?P<key>[0-9a-z]{32})?', EmailView.as_view(),
                                                name="archive_email_view"),
)

src/super_archives/models.py
# -*- coding: utf-8 -*-

import urllib

from uuid import uuid4
from hashlib import md5

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.cache import cache
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse, NoReverseMatch
from django.utils.translation import ugettext_lazy as _

from html2text import html2text
from haystack.query import SearchQuerySet
from taggit.managers import TaggableManager
from hitcounter.models import HitCounterModelMixin

from .managers import NotSpamManager, MostVotedManager, HighestScore
from .utils import blocks
from .utils.etiquetador import etiquetador


User = get_user_model()


class EmailAddressValidation(models.Model):
    address = models.EmailField(unique=True)
    user = models.ForeignKey(User, null=True,
                             related_name='emails_not_validated')
    validation_key = models.CharField(max_length=32, null=True,
                                      default=lambda: uuid4().hex)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'address')


class EmailAddress(models.Model):
    user = models.ForeignKey(User, null=True, related_name='emails',
                             on_delete=models.SET_NULL)
    address = models.EmailField(unique=True)
    real_name = models.CharField(max_length=64, blank=True, db_index=True)
    md5 = models.CharField(max_length=32, null=True)

    class Meta:
        ordering = ('id', )

    def save(self, *args, **kwargs):
        self.md5 = md5(self.address).hexdigest()
        super(EmailAddress, self).save(*args, **kwargs)

    def get_full_name(self):
        if self.user and self.user.get_full_name():
            return self.user.get_full_name()
        else:
            return self.real_name

    def get_full_name_or_anonymous(self):
        return self.get_full_name() or _('Anonymous')

    def __unicode__(self):
        return '"%s" <%s>' % (self.get_full_name(), self.address)


class MailingList(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    description = models.TextField()
    logo = models.FileField(upload_to='list_logo') #TODO
    last_imported_index = models.IntegerField(default=0)

    def get_absolute_url(self):
        params = {
            'list': self.name,
            'type': 'thread',
            'order': 'latest',
        }
        return u'{}?{}'.format(reverse('haystack_search'),
                               urllib.urlencode(params))

    def __unicode__(self):
        return self.name


class MailingListMembership(models.Model):
    user = models.ForeignKey(User)
    mailinglist = models.ForeignKey(MailingList)

    def __unicode__(self):
        return '%s on %s' % (self.user.email, self.mailinglist.name)


class Keyword(models.Model):
    keyword = models.CharField(max_length='128')
    weight = models.IntegerField(default=0)
    thread = models.ForeignKey('Thread')

    class Meta:
        ordering = ('?', ) # random order

    def __unicode__(self):
        return self.keyword


class Thread(models.Model, HitCounterModelMixin):

    subject_token = models.CharField(max_length=512)
    mailinglist = models.ForeignKey(MailingList,
                                    verbose_name=_(u"Mailing List"),
                                    help_text=_(u"The Mailing List where is the thread"))
    latest_message = models.OneToOneField('Message', null=True,
                                                     related_name='+',
                                                     verbose_name=_(u"Latest message"),
                                                     help_text=_(u"Latest message posted"))
    score = models.IntegerField(default=0, verbose_name=_(u"Score"), help_text=_(u"Thread score"))
    spam = models.BooleanField(default=False)

    highest_score = HighestScore()
    all_objects = models.Manager()
    objects = NotSpamManager()
    tags = TaggableManager()

    class Meta:
        verbose_name = _(u"Thread")
        verbose_name_plural = _(u"Threads")
        unique_together = ('subject_token', 'mailinglist')
        ordering = ('-latest_message__received_time', )

    @models.permalink
    def get_absolute_url(self):
        return ('thread_view', [self.mailinglist, self.subject_token])

    def update_keywords(self):
        blocks = MessageBlock.objects.filter(message__thread__pk=self.pk,
                                             is_reply=False)

        self.tags.clear()

        text = u'\n'.join(map(unicode, blocks))
        tags = etiquetador(html2text(text))

        for tag, weight in tags:
            keyword, created = Keyword.objects.get_or_create(thread=self,
                                                             keyword=tag)
            if created or keyword.weight != weight:
                keyword.weight = weight
                keyword.save()

            if weight >= 3:
                self.tags.add(tag)

        # removing old tags not used anylonger
        if tags:
            qs = Keyword.objects.filter(thread=self)
            qs = qs.exclude(keyword__in=zip(*tags)[0])
            qs.delete()

    def get_related(self):
        query_string = u' '.join(self.tags.names())
        if query_string:
            query_set = SearchQuerySet().exclude(django_id=self.pk)
            return query_set.filter(content=query_string, type='thread')

        return tuple()

    def __unicode__(self):
        return '%s - %s (%s)' % (self.id,
                                 self.subject_token,
                                 self.message_set.count())

    def update_score(self):
        """Update the relevance score for this thread.

        The score is calculated with the following variables:

        * vote_weight: 100 - (minus) 1 for each 3 days since
          voted with minimum of 5.
        * replies_weight: 300 - (minus) 1 for each 3 days since
          replied with minimum of 5.
        * page_view_weight: 10.

        * vote_score: sum(vote_weight)
        * replies_score: sum(replies_weight)
        * page_view_score: sum(page_view_weight)

        * score = (vote_score + replies_score + page_view_score) // 10
        with minimum of 0 and maximum of 5000

        """

        if not self.subject_token:
            return

        # Save this pseudo now to avoid calling the
        #   function N times in the loops below
        now = timezone.now()
        days_ago = lambda date: (now - date).days
        get_score = lambda weight, created: \
                                  max(weight - (days_ago(created) // 3), 5)

        vote_score = 0
        replies_score = 0
        for msg in self.message_set.all():
            # Calculate replies_score
            replies_score += get_score(300, msg.received_time)

            # Calculate vote_score
            for vote in msg.vote_set.all():
                vote_score += get_score(100, vote.created)

        # Calculate page_view_score
        page_view_score = self.hits * 10

        self.score = (page_view_score + vote_score + replies_score) // 10
        self.save()


class Vote(models.Model):
    user = models.ForeignKey(User)
    message = models.ForeignKey('Message')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'message')

    def __unicode__(self):
        return 'Vote on %s by %s' % (self.Message.id,
                                     self.user.username)


class Message(models.Model):

    from_address = models.ForeignKey(EmailAddress, db_index=True)
    thread = models.ForeignKey(Thread, null=True, db_index=True)
    # RFC 2822 recommends to use 78 chars + CRLF (so 80 chars) for
    #   the max_length of a subject but most of implementations
    #   goes for 256. We use 512 just in case.
    subject = models.CharField(max_length=512, db_index=True,
                               verbose_name=_(u"Subject"),
                               help_text=_(u"Please enter a message subject"))
    subject_clean = models.CharField(max_length=512, db_index=True)
    body = models.TextField(default='',
                            verbose_name=_(u"Message body"),
                            help_text=_(u"Please enter a message body"))
    received_time = models.DateTimeField(db_index=True)
    message_id = models.CharField(max_length=512)
    spam = models.BooleanField(default=False)

    all_objects = models.Manager()
    objects = NotSpamManager()
    most_voted = MostVotedManager()

    class Meta:
        verbose_name = _(u"Message")
        verbose_name_plural = _(u"Messages")
        unique_together = ('thread', 'message_id')
        ordering = ('received_time', )

    def __unicode__(self):
        return '(%s) %s: %s' % (self.id,
                                self.from_address.get_full_name(),
                                self.subject_clean)

    def update_blocks(self):
        # delete all blocks for that message
        self.blocks.all().delete()

        for i, block in enumerate(blocks.EmailBlockParser(self)):
            MessageBlock.from_emailblock(block, self, i)

    @property
    def mailinglist(self):
        if not self.thread:
            return None

        return self.thread.mailinglist

    def vote_list(self):
        """Return a list of user that voted in this message."""
        return [vote.user for vote in self.vote_set.iterator()]

    def votes_count(self):
        return len(self.vote_list())

    def vote(self, user):
        Vote.objects.create(
            message=self,
            user=user
        )

    def unvote(self, user):
        Vote.objects.get(
            message=self,
            user=user
        ).delete()

    @property
    def url(self):
        """Shortcut to get thread url"""
        return reverse('thread_view', args=[self.mailinglist.name,

src/super_archives/templates/message-preview.html
{% load i18n tz highlight %}

<li class="preview-message">
<span class="glyphicon glyphicon-{{ result.icon_name }}" title="{{ result.type }}"></span>

{% if result.tag %}
<a href="{% firstof result.mailinglist_url result.mailinglist.get_absolute_url result.url %}">
  <span class="label label-primary">{{ result.tag }}</span>
</a>
{% endif %}

{% if result.title %}
  <a href="{{ result.url }}{% if result.type == 'thread' and result.latest_message_pk %}#msg-{{ result.latest_message_pk }}{% elif result.type == 'thread' and result.pk %}#msg-{{ result.pk }}{% endif %}" {% if result.latest_description %}title="{{ result.latest_description|escape|truncatechars:150 }}"{% elif result.description %}title="{{ result.description|escape|truncatechars:150 }}"{% endif %}>
    <span class="subject">
      <!-- a striptags filter was raising an error here because using with highlight -->
      {% if query %}
        {% highlight result.title with query max_length "1000" %}
      {% else %}
        {{ result.title }}
      {% endif %}
    </span>
  </a>
{% endif %}

{% if result.description %}
      <!-- a striptags filter was raising an error here because using with highlight -->
  <span class="quiet">- {% if query %}
    {% highlight result.description with query max_length "150" %}
  {% else %}
    {% if result.latest_description %}
      {{ result.latest_description|striptags|escape|truncatechars:150 }}
    {% elif result.description %}
      {{ result.description|striptags|escape|truncatechars:150 }}
    {% endif %}
  {% endif %}
  </span>
{% endif %}

{% if result.fullname or result.modified or result.modified_by %}
  <div class="quiet">
    {% if result.modified_by %}
      <span class="pull-left">{% trans "by" %}
        {% if result.modified_by_url %}
          <a href="{{ result.modified_by_url }}">
        {% else %}
          <span>
        {% endif %}

        {% if query %}
          {% highlight result.modified_by with query %}
        {% else %}
          {{ result.modified_by }}
        {% endif %}

        {% if result.modified_by_url %}
          </a>
        {% else %}
          </span>
        {% endif %}
      </span>
    {% else %}
      <span class="pull-left">{% trans "by" %} {% trans "Anonymous" %}</span>
    {% endif %}
    {% if result.modified %}
      <span class="pull-right">{{ result.modified|localtime|timesince }} {% trans "ago" %}</span>
    {% endif %}
  </div>
{% endif %}
</li>

src/super_archives/templates/message-thread.html
{% extends "base.html" %}
{% load i18n tz superarchives %}

{% trans "Anonymous" as anonymous %}

{% block title %}{{ first_msg.subject_clean }}{% endblock %}

{% block head_js %}

<script>
  function vote_done_callback(step) {
    console.debug('(un)vote successfuly (step ' + step + ')');
    var $btn = $(this);
    var step;

    if ($btn.hasClass('btn-default')) {
      step = 1;
    } else {
      step = -1;
    }

    $btn.prev('.vote-count').text(function(self, count) {
        return parseInt(count) + step;
    });

    $btn.toggleClass('btn-success');
    $btn.toggleClass('btn-default');
    $btn.button('reset')
  }

  function vote_fail_callback(jqXHR, textStatus, errorThrown) {
    var msg;

    if (jqXHR.status === 403) {
      msg = " {% trans 'You must login before voting.' %}"

      $('#alert-js #alert-message').html(msg);
      $('#alert-js').show();
      scroll(0, 0);
    }

  }

  function vote(event) {
    var $ajax;
    var $btn = $(this);
    var $msg = $(this).parents('.email-message');

    var method;
    var csrftoken = $.cookie('csrftoken');
    var msg_id = $msg.attr('id').split('-')[1];

    if($btn.hasClass('btn-default')) {
        method = 'PUT';
    } else {
        method = 'DELETE';
    }

    console.debug('trying to vote');
    $btn.button('loading');
    $ajax = $.ajax({
      url: "/api/message/" + msg_id + "/vote",
      type: method,
      context: $btn.get(0),
      beforeSend: function(xhr, settings) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    });
    $ajax.done(vote_done_callback);
    $ajax.fail(vote_fail_callback);
  }

  function scrollToAnchor(aid){
    var aTag = $(aid);
    console.log(aTag);
    $('html, body').animate({scrollTop: aTag.offset().top}, 800);
  }

  {% if user.is_active %}
  function focus_reply(event) {
    scrollToAnchor('#msg-reply');
    $('textarea', '#msg-reply').focus();
  }
  {% endif %}

  // Binding functions
  $(function() {
    $(".panel-heading").on('click', function(event) {
        var $target = $(event.target);
        // Do not collapse the the message if the clicked element (target)
        //  is a button or a link
        if($target.hasClass('btn') || $target.is('a') || $target.parent().is('a')) {
            return;
        }

        $(this).next('.panel-collapse').collapse('toggle');
    });

    $('.vote.btn', this).on('click', vote);
    {% if user.is_active %}
      $('.reply.btn', this).on('click', focus_reply);
    {% endif %}

    $('.message-link').popover({'placement': 'right'});
  });

</script>

{% endblock %}

{% block main-content %}
<div class="row">

  <div class="col-lg-12">
    <h2>{{ first_msg.subject_clean }}</h2>
    <hr />
  </div>

  <div class="col-lg-9 col-md-9 col-sm-12">
    <ul class="unstyled-list">
    {% for email in emails %}
      {% include "superarchives/includes/message.html" with userprofile=email.from_address.user emailaddress=email.from_address fullname=email.from_address.get_full_name_or_anonymous %}
    {% endfor %}

    {% if user.is_active %}
      {% include "superarchives/includes/message.html" with userprofile=user emailaddress=user.email fullname=user.get_full_name reply=True %}
    {% endif %}
    </ul>
  </div>

  <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
    <h4><strong>{% trans "Order by" %}:</strong></h4>
    <ul class="unstyled-list">
      <li>
        <span class="glyphicon glyphicon-chevron-right"></span>
        <a href="{% append_to_get order='voted' %}">{% trans "Votes" %}</a>
      </li>
      <li>
        <span class="glyphicon glyphicon-chevron-right"></span>
        <a href="{% append_to_get order='date' %}">{% trans "Date" %}</a>
      </li>
    </ul>

    {% if thread.get_related %}
    <h4><strong>{% trans "Related:" %}</strong></h4>
    <ul class="unstyled-list">
      {% for similar in thread.get_related|slice:":10" %}
      <li>
        <span class="label label-primary label-small">{{ similar.tag }}</span>
        <a href="{{ similar.url }}">{{ similar.title|truncatechars:50 }}</a>
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    <h4><strong>{% trans "Statistics:" %}</strong></h4>
    <ul class="unstyled-list">
      <li>
        <span class="glyphicon glyphicon-chevron-right"></span>
        {% trans "started at" %}
        <h5>{{ first_msg.received_time|localtime|timesince }} {% trans "ago" %}</h5>
      </li>

      <li>
        <span class="glyphicon glyphicon-chevron-right"></span>
        {% trans "viewed" %}
        <h5>{{ pagehits }} {% trans "times" %}</h5>
      </li>
      <li>
        <span class="glyphicon glyphicon-chevron-right"></span>
        {% trans "answered" %}
        <h5>{{ emails|length }} {% trans "times" %}</h5>
      </li>
      <li>
        <span class="glyphicon glyphicon-chevron-right"></span>
        {% trans "voted" %}
        <h5>{{ total_votes }} {% trans "times" %}</h5>
      </li>
    </ul>

    {% if thread.keyword_set.count %}
    <h4><strong>{% trans "Tags:" %}</strong></h4>
    <div class="tag-cloud">
      {% for keyword in thread.keyword_set.all %}
        <a class="tag size-{{ keyword.weight }}" href="{% url 'haystack_search' %}?q={{ keyword }}">{{ keyword|escape }}</a>
      {% endfor %}
    </div>
    {% endif %}

  </div>

</div>
{% endblock %}