src/accounts/urls.py
from django.conf.urls import patterns, include, url

from .views import (UserProfileDetailView, UserProfileUpdateView,
                    ManageUserSubscriptionsView, ChangeXMPPPasswordView)

from accounts import views

urlpatterns = patterns('',
    url(r'^register/$', 'accounts.views.signup', name='signup'),

    url(r'^change-password/$',
        ChangeXMPPPasswordView.as_view(), name='change_password'),

    url(r'^logout/?$',  'accounts.views.logoutColab'),

    url(r'^(?P<username>[\w@+.-]+)/?$',
        UserProfileDetailView.as_view(), name='user_profile'),

    url(r'^(?P<username>[\w@+.-]+)/edit/?$',
        UserProfileUpdateView.as_view(), name='user_profile_update'),

    url(r'^(?P<username>[\w@+.-]+)/subscriptions/?$',
        ManageUserSubscriptionsView.as_view(), name='user_list_subscriptions'),
)

src/api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from tastypie.api import Api

from .resources import (UserResource, EmailAddressResource, MessageResource,
                     RevisionResource, TicketResource, WikiResource)
from .views import VoteView


api = Api(api_name='v1')
api.register(UserResource())
api.register(EmailAddressResource())
api.register(MessageResource())
api.register(RevisionResource())
api.register(TicketResource())
api.register(WikiResource())


urlpatterns = patterns('',
    url(r'message/(?P<msg_id>\d+)/vote$', VoteView.as_view()),

    # tastypie urls
    url(r'', include(api.urls)),
)

src/colab/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib import admin

from accounts.models import User
from search.forms import ColabSearchForm
from super_archives.models import Message


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'home.views.index', name='home'),
    url(r'^robots.txt$', 'home.views.robots', name='robots'),

    url(r'^open-data/$', TemplateView.as_view(template_name='open-data.html'),
        name='opendata'),

    url(r'^search/', include('search.urls')),
    url(r'^archives/', include('super_archives.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^rss/', include('rss.urls')),

    url(r'^user/', include('accounts.urls')),    # Kept for backwards compatibility
    url(r'^signup/', include('accounts.urls')),  # (same here) TODO: move to nginx
    url(r'^account/', include('accounts.urls')),

    url(r'', include('django_browserid.urls')),

    url(r'^planet/', include('feedzilla.urls')),

    url(r'paste/', include('dpaste.urls.dpaste')),

    # Uncomment the next line to enable the admin:
    url(r'^colab/admin/', include(admin.site.urls)),

    url(r'^', include('proxy.urls')),
)

if settings.DEBUG:
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/badger/models.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import ugettext_lazy as _
from i18n_model.models import I18nModel


class Badge(models.Model):
    COMPARISON_CHOICES = (
        (u'gte', _(u'Greater than or equal')),
        (u'lte', _(u'less than or equal')),
        (u'equal', _(u'Equal')),
        (u'biggest', _(u'Biggest')),
    )
    TYPE_CHOICES = (
        (u'auto', _(u'Automatically')),
        (u'manual', _(u'Manual')),
    )
    USER_ATTR_CHOICES = (
        (u'messages', _(u'Messages')),
        (u'contributions', _(u'Contributions')),
        (u'wikis', _(u'Wikis')),
        (u'revisions', _(u'Revisions')),
        (u'tickets', _(u'Ticket')),
    )
    USER_ATTR_OPTS = {
        u'messages': u'message_count',
        u'revisions': u'changeset_count',
        u'tickets': u'ticket_count',
        u'wikis': u'wiki_count',
        u'contributions': u'contribution_count',
    }

    title = models.CharField(_(u'Title'), max_length=200, blank=True,
                             null=True)
    description = models.CharField(_(u'Description'), max_length=200,
                                   blank=True, null=True)
    image_base64 = models.TextField(_(u'Image'))
    type = models.CharField(_(u'Type'), max_length=200, choices=TYPE_CHOICES)
    user_attr = models.CharField(
        _(u'User attribute'),max_length=100,
        choices=USER_ATTR_CHOICES,
        blank=True,
        null=True,
    )
    comparison = models.CharField(
        _(u'Comparison'),
        max_length=10,
        choices=COMPARISON_CHOICES,
        blank=True,
        null=True
    )
    value = models.PositiveSmallIntegerField(
        _(u'Value'),
        blank=True,
        null=True
    )
    awardees = models.ManyToManyField(
        get_user_model(),
        verbose_name=_(u'Awardees'),
        blank=True,
        null=True
    )
    order = models.PositiveSmallIntegerField(_(u'Order'), default=100)

    class Meta:
        verbose_name = _(u'Badge')
        verbose_name_plural = _(u'Badges')
        ordering = ['order', ]

    def __unicode__(self):
        return u'{} ({}, {})'.format(
            self.title,
            self.get_user_attr_display(),
            self.get_type_display(),
        )


class BadgeI18N(I18nModel):
    class Meta:
        source_model = Badge
        translation_fields = ('title', 'description')

src/accounts/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from conversejs.models import XMPPAccount

from accounts.utils import mailman
from super_archives.models import MailingList
from .utils.validators import validate_social_account

User = get_user_model()


class SocialAccountField(forms.Field):
    def __init__(self, *args, **kwargs):
        self.url = kwargs.pop('url', None)
        super(SocialAccountField, self).__init__(*args, **kwargs)

    def validate(self, value):
        super(SocialAccountField, self).validate(value)

        if value and not validate_social_account(value, self.url):
            raise forms.ValidationError(_('Social account does not exist'),
                                        code='social-account-doesnot-exist')


class UserForm(forms.ModelForm):
    required = ('first_name', 'last_name', 'email', 'username')

    class Meta:
        model = User

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            # Adds form-control class to all form fields
            field.widget.attrs.update({'class': 'form-control'})

            # Set UserForm.required fields as required
            if field_name in UserForm.required:
                field.required = True


class UserCreationForm(UserForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')


class UserUpdateForm(UserForm):
    bio = forms.CharField(
        widget=forms.Textarea(attrs={'rows': '6', 'maxlength': '200'}),
        max_length=200,
        label=_(u'Bio'),
        help_text=_(u'Write something about you in 200 characters or less.'),
        required=False,
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name',
                  'institution', 'role', 'twitter', 'facebook',
                  'google_talk', 'github', 'webpage', 'bio')

    twitter = SocialAccountField(url='https://twitter.com/', required=False)
    facebook = SocialAccountField(url='https://graph.facebook.com/', required=False)


class ListsForm(forms.Form):
    LISTS_NAMES = ((
        listname, u'{} ({})'.format(listname, description)
    ) for listname, description in mailman.all_lists(description=True))

    lists = forms.MultipleChoiceField(label=_(u'Mailing lists'),
                                      required=False,
                                      widget=forms.CheckboxSelectMultiple,
                                      choices=LISTS_NAMES)


class ChangeXMPPPasswordForm(forms.ModelForm):
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = XMPPAccount
        fields = ('password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(ChangeXMPPPasswordForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            # Adds form-control class to all form fields
            field.widget.attrs.update({'class': 'form-control'})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                _("Password mismatch"),
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        self.instance.password = self.cleaned_data['password2']
        if commit:
            self.instance.save()
        return self.instance

src/accounts/views.py
#!/usr/bin/env python
# encoding: utf-8

import datetime

from collections import OrderedDict

from django.contrib.auth.views import logout
from django.contrib import messages
from django.db import transaction
from django.db.models import Count
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
from django.views.generic import DetailView, UpdateView
from django.utils.decorators import method_decorator

from django.http import HttpResponse
from conversejs import xmpp
from conversejs.models import XMPPAccount
from haystack.query import SearchQuerySet

from super_archives.models import EmailAddress, Message
from super_archives.utils.email import send_email_lists
from search.utils import trans
from proxy.models import WikiCollabCount, TicketCollabCount
from .forms import (UserCreationForm, ListsForm, UserUpdateForm,
                    ChangeXMPPPasswordForm)
from .errors import XMPPChangePwdException
from .utils import mailman


class UserProfileBaseMixin(object):
    model = get_user_model()
    slug_field = 'username'
    slug_url_kwarg = 'username'
    context_object_name = 'user_'


class UserProfileUpdateView(UserProfileBaseMixin, UpdateView):
    template_name = 'accounts/user_update_form.html'
    form_class = UserUpdateForm

    def get_success_url(self):
        return reverse('user_profile', kwargs={'username': self.object.username})

    def get_object(self, *args, **kwargs):
        obj = super(UserProfileUpdateView, self).get_object(*args, **kwargs)
        if self.request.user != obj and not self.request.user.is_superuser:
            raise PermissionDenied

        return obj


class UserProfileDetailView(UserProfileBaseMixin, DetailView):
    template_name = 'accounts/user_detail.html'

    def get_context_data(self, **kwargs):
        user = self.object
        context = {}

        count_types = OrderedDict()

        fields_or_lookup = (
            {'collaborators__contains': user.username},
            {'fullname_and_username__contains': user.username},
        )

        counter_class = {
            'wiki': WikiCollabCount,
            'ticket': TicketCollabCount,
        }

        messages = Message.objects.filter(from_address__user__pk=user.pk)
        for type in ['thread', 'ticket', 'wiki', 'changeset', 'attachment']:
            CounterClass = counter_class.get(type)
            if CounterClass:
                try:
                    counter = CounterClass.objects.get(author=user.username)
                except CounterClass.DoesNotExist:
                    count_types[trans(type)] = 0
                else:
                    count_types[trans(type)] = counter.count
            elif type == 'thread':
                count_types[trans(type)] = messages.count()
            else:
                sqs = SearchQuerySet()
                for filter_or in fields_or_lookup:
                    sqs = sqs.filter_or(type=type, **filter_or)
                count_types[trans(type)] = sqs.count()

        context['type_count'] = count_types

        sqs = SearchQuerySet()
        for filter_or in fields_or_lookup:
            sqs = sqs.filter_or(**filter_or).exclude(type='thread')

        context['results'] = sqs.order_by('-modified', '-created')[:10]

        email_pks = [addr.pk for addr in user.emails.iterator()]
        query = Message.objects.filter(from_address__in=email_pks)
        query = query.order_by('-received_time')
        context['emails'] = query[:10]

        count_by = 'thread__mailinglist__name'
        context['list_activity'] = dict(messages.values_list(count_by)\
                                           .annotate(Count(count_by))\
                                           .order_by(count_by))

        context.update(kwargs)
        return super(UserProfileDetailView, self).get_context_data(**context)


def logoutColab(request):
       response = logout(request, next_page='/')
       response.delete_cookie('_redmine_session')
       response.delete_cookie('_gitlab_session')
       return response


def signup(request):
    # If the request method is GET just return the form
    if request.method == 'GET':
        user_form = UserCreationForm()
        lists_form = ListsForm()
        return render(request, 'accounts/user_create_form.html',
                      {'user_form': user_form, 'lists_form': lists_form})

    user_form = UserCreationForm(request.POST)
    lists_form = ListsForm(request.POST)

    if not user_form.is_valid() or not lists_form.is_valid():
        return render(request, 'accounts/user_create_form.html',
                      {'user_form': user_form, 'lists_form': lists_form})

    user = user_form.save()

    mailing_lists = lists_form.cleaned_data.get('lists')
    if mailing_lists:
        send_email_lists(user, mailing_lists)

    # Check if the user's email have been used previously
    #   in the mainling lists to link the user to old messages
    email_addr, created = EmailAddress.objects.get_or_create(address=user.email)
    if created:
        email_addr.real_name = user.get_full_name()

    email_addr.user = user
    email_addr.save()

    messages.success(request, _('Your profile has been created!'))
    messages.warning(request, _('You must login to validated your profile. '
                                'Profiles not validated are deleted in 24h.'))

    return redirect('user_profile', username=user.username)


class ManageUserSubscriptionsView(UserProfileBaseMixin, DetailView):
    http_method_names = [u'get', u'post']
    template_name = u'accounts/manage_subscriptions.html'

    def get_object(self, *args, **kwargs):
        obj = super(ManageUserSubscriptionsView, self).get_object(*args,
                                                                  **kwargs)
        if self.request.user != obj and not self.request.user.is_superuser:
            raise PermissionDenied

        return obj

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        for email in user.emails.values_list('address', flat=True):
            lists = self.request.POST.getlist(email)
            user.update_subscription(email, lists)

        return redirect('user_profile', username=user.username)

    def get_context_data(self, **kwargs):
        context = {}
        context['membership'] = {}

        user = self.get_object()
        emails = user.emails.values_list('address', flat=True)
        all_lists = mailman.all_lists(description=True)

        for email in emails:
            lists = []
            lists_for_address = mailman.address_lists(email)
            for listname, description in all_lists:
                if listname in lists_for_address:
                    checked = True
                else:
                    checked = False
                lists.append((
                    {'listname': listname, 'description': description},
                    checked
                ))

            context['membership'].update({email: lists})

        context.update(kwargs)

        return super(ManageUserSubscriptionsView, self).get_context_data(**context)


class ChangeXMPPPasswordView(UpdateView):
    model = XMPPAccount
    form_class = ChangeXMPPPasswordForm
    fields = ['password', ]
    template_name = 'accounts/change_password.html'

    def get_success_url(self):
        return reverse('user_profile', kwargs={
            'username': self.request.user.username
        })

    def get_object(self, queryset=None):
        obj = get_object_or_404(XMPPAccount, user=self.request.user.pk)
        self.old_password = obj.password
        return obj

    def form_valid(self, form):
        transaction.set_autocommit(False)

        response = super(ChangeXMPPPasswordView, self).form_valid(form)

        changed = xmpp.change_password(
            self.object.jid,
            self.old_password,
            form.cleaned_data['password1']
        )

        if not changed:
            messages.error(
                self.request,
                _(u'Could not change your password. Please, try again later.')
            )
            transaction.rollback()
            return response
        else:
            transaction.commit()

        messages.success(
            self.request,
            _("You've changed your password successfully!")
        )
        return response

src/accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load i18n %}

{% block main-content %}
<form method="POST" role="form">
  {% csrf_token %}
  <div class="row">
    <h2>{% trans "Change XMPP Client and SVN Password" %}</h2>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
      {% for field in form %}
        <div class="form-group required{% if field.errors %} alert alert-danger has-error{% endif %}">
          <label for="{{ field.name }}" class="control-label">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>
      {% endfor %}
      <button class="btn btn-primary">{% trans "Change Password" %}</button>
    </div>
  </div>
</form>
{% endblock %}

src/accounts/templates/accounts/manage_subscriptions.html
{% extends 'base.html' %}
{% load i18n gravatar %}

{% block main-content %}

  <h2>{% blocktrans %}Group Subscriptions{% endblocktrans %}</h2>
  <h3>{% gravatar user_.email 50 %} {{ user_.get_full_name }} ({{ user_.username }})</h3>
  <br>

  <form method='post'>
    {% csrf_token %}

    <div class="row">
      {% for email, lists in membership.items %}
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">{{ email }}</h3>
          </div>
          <div class="panel-body">
            {% for list, checked in lists %}
              <div class="checkbox" title="{{ list.description }}">
                <label>
                  <input name="{{ email }}" value="{{ list.listname }}" type="checkbox" {% if checked %}checked{% endif%}>{{ list.listname }}</input>
                </label>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="row">
      <div class="text-center">
        <button class="btn btn-lg btn-primary" type="submit">{% trans 'Update subscriptions' %}</button>
      </div>
    </div>

  </form>

 <br><br>
 <br><br>

{% endblock %}

src/accounts/templates/accounts/user_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% block main-content %}

<h2>{% trans "Sign up" %}</h2>

<div class="row">
  {% if form.errors %}
  <div class="alert alert-danger">
    <b>{% trans "Please correct the errors below and try again" %}</b>
  </div>
  {% endif %}
</div>


<p class="required">
  <label>{% trans "Required fields" %}</label>
</p>

<form action="." method="post" role="form" class="form-horizontal signup">
  {% csrf_token %}

  <div class="row">

    <div>
      <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12" style="display: inline-block; vertical-align:top;">
        <div class="well">
          <fieldset>
            <legend>{% trans 'Personal Information' %}</legend>
            {% for field in user_form %}
              <div class="form-group{% if field.field.required %} required{% endif %}{% if field.errors %} alert alert-danger has-error{% endif %}">
                <label for="{{ field.name }}" class="control-label">
                  {{ field.label }}
                </label>
                {{ field }}
                {{ field.errors }}
              </div>
            {% endfor %}
          </fieldset>
        </div>
      </div>

      <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12" style="display: inline-block; vertical-align:top;">
        <div class="well">
          <fieldset>
            <legend>{% trans 'Subscribe to groups' %}</legend>
            {% for choice in lists_form.lists %}
              <div class="checkbox">{{ choice }}</div>
            {% endfor %}
            {{ lists_form.errors }}
          </fieldset>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="submit">
      <input type="submit" value="{% trans 'Register' %}" class="btn btn-primary btn-lg btn-block">
    </div>
  </div>

</form>

{% endblock %}

src/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}

{% load i18n gravatar i18n_model %}

{% block title %}Perfil{% endblock %}

{% block head_js %}
  {% trans "Messages" as group_collabs %}
  {% trans "Contributions" as type_collabs %}

  {% include "pizza-chart.html" with chart_data=type_count chart_div="collabs" chart_height=300 name=type_collabs %}
  {% include "pizza-chart.html" with chart_data=list_activity chart_div="collabs2" chart_height=300 name=group_collabs %}
{% endblock %}

{% block main-content %}

  <div id="user-profile" class="row">
    <div class="vcard col-lg-4 col-md-4 col-sm-5">
      <div class="thumbnail">
        {% gravatar user_.email 200 %}
      </div>

      <h1>
        <span>{{ user_.get_full_name }}</span>
        <em>{{ user_.username }}</em>
      </h1>

      {% if request.user == user_ or request.user.is_superuser %}
        <a class="btn btn-info" href="{% url 'user_profile_update' user_ %}"><span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;{% trans "edit profile"|title %}</a>
        <a class="btn btn-info" href="{% url 'user_list_subscriptions' user_ %}"><span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;{% trans "group membership"|title %}</a>
      {% endif %}

      {% if request.user.is_active %}
        {% if user_.bio %}
          <div class="divider"></div>
          <ul class="unstyled-list">
            <li>
              <strong>{% trans 'Bio' %}</strong>
            </li>
            <li class="text-muted"> {{ user_.bio }}</li>
          </ul>
        {% endif %}
      {% endif %}

      <div class="divider"></div>
      {% if request.user.is_active %}
        <ul class="unstyled-list">
          <li><span class="icon-envelope icon-fixed-width"></span> <a href="mailto:{{ user_.email }}">{{ user_.email }}</a></li>
        </ul>
        <div class="divider"></div>
      {% endif %}

      <ul class="unstyled-list">
        {% if user_.institution or user_.role %}
          <li>
            <span class="icon-briefcase icon-fixed-width"></span>
            {{ user_.role }}
            {% if user_.institution and user_.role %}-{% endif %}
            {{ user_.institution }}
          </li>
        {% endif %}
        {% if request.user.is_active %}
          <li>
            {% if user_.twitter %}
              <span class="icon-twitter icon-fixed-width" title="{% trans 'Twitter account' %}"></span> <a target="_blank" href="{{ user_.twitter_link }}" title="{% trans 'Twitter account' %}">{{ user_.twitter }}</a>
            {% endif %}
            {% if user_.facebook %}
              <span class="icon-facebook icon-fixed-width" title="{% trans 'Facebook account' %}"></span> <a target="_blank" href="{{ user_.facebook_link }}" title="{% trans 'Facebook account' %}">{{ user_.facebook }}</a>
            {% endif %}
          </li>

          {% if user_.google_talk %}
            <li><span class="icon-google-plus icon-fixed-width" title="{% trans 'Google talk account' %}"></span> {{ user_.google_talk }}</li>
          {% endif %}

          {% if user_.github %}
            <li><span class="icon-github icon-fixed-width" title="{% trans 'Github account' %}"></span> <a target="_blank" href="https://github.com/{{ user_.github }}">{{ user_.github }}</a></li>
          {% endif %}

          {% if user_.webpage %}
            <li><span class="icon-link icon-fixed-width" title="{% trans 'Personal webpage' %}"></span> <a target="_blank" href="{{ user_.webpage }}" title="{% trans 'Personal webpage' %}">{{ user_.webpage }}</a></li>
          {% endif %}
        {% endif %}
      </ul>

      {% if user_.mailinglists %}
        <b>{% trans 'Groups: ' %}</b>
        {% for list in user_.mailinglists %}
          <a href="{% url 'haystack_search' %}?order=latest&amp;type=thread&amp;list={{ list }}"><span class="label label-primary">{{ list }}</span></a>
        {% endfor %}
      {% endif %}

      <div class="divider"></div>

    </div>

    <div class="col-lg-4 col-md-4 col-sm-7">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{% trans "Contributions by Type" %}</h3>
        </div>
        <div class="panel-body">
          <div id="collabs"></div>
        </div>
      </div>
    </div>


    <div class="col-lg-4 col-md-4 col-sm-7">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{% trans "Participation by Group" %}</h3>
        </div>
        <div class="panel-body">
          <div id="collabs2"></div>
        </div>
      </div>
    </div>


    {% if user_.badge_set.exists %}
      <div class="col-lg-8 col-md-12 col-sm-7">
        <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">{% trans "Badges" %}</h3>
            </div>
            <div class="panel-body">
              <div>
                {% for badge in user_.badge_set.all %}
                  {% translate badge as badge_trans %}
                  <img src="data:image/png;base64,{{ badge.image_base64 }}" title="({{ badge_trans.title }}) {{ badge_trans.description }}" />
                {% endfor %}
              </div>
            </div>
        </div>
      </div>
    {% endif %}

  </div> <!-- End of user-profile row -->

  <div class="row">

    <div class="col-lg-6 col-md-6 col-sm-12">
      <h3>{% trans "Latest posted" %} </h3>
      <ul class="message-list">
      {% for doc in emails %}
        {% include "message-preview.html" with result=doc %}
      {% empty %}
        <li>{% trans "There are no posts by this user so far." %}</li>
      {% endfor %}
      </ul>
      <a href="{% url 'haystack_search' %}?type=thread&amp;author={{ user_.username }}">
        {% trans "View more discussions..." %}
      </a>
      <div>&nbsp;</div>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-12">
      <h3>{% trans "Contributions" %}</h3>
      <ul class="message-list">
      {% for result in results %}
        {% include "message-preview.html" %}
      {% empty %}
        <li>{% trans "No contributions of this user so far." %}</li>
      {% endfor %}
      </ul>
      <a href="{% url 'haystack_search' %}?order=latest&amp;collaborators={{ user_.username }}">
        {% trans "View more contributions..." %}
      </a>
      <div>&nbsp;</div>
    </div>

  </div>

{% endblock %}